
name: Foo

on:
  push:
    branches: [work]

jobs:
  release:
    runs-on: macos-10.15
    timeout-minutes: 15
    steps:
      #
      # Setup
      #

      - name: "Checkout Project"
        uses: actions/checkout@v2

      - name: "Select latest Xcode 12"
        uses: devbotsxyz/xcode-select@v1
        with:
          version: "12"

      - name: "Import Certificate: Development"
        uses: devbotsxyz/import-signing-certificate@main
        with:
          certificate-data: ${{ secrets.DEVELOPMENT_CERTIFICATE_DATA }}
          certificate-passphrase: ${{ secrets.DEVELOPMENT_CERTIFICATE_PASSPHRASE }}
          keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}

      - name: "Fetch Development Provisioning Profiles"
        uses: st3fan/fetch-provisioning-profiles@main
        with:
          appstore-connect-api-key: ${{ secrets.APPSTORE_CONNECT_KEY }}
          appstore-connect-api-key-id: ${{ secrets.APPSTORE_CONNECT_KEY_ID }}
          appstore-connect-api-issuer: ${{ secrets.APPSTORE_CONNECT_ISSUER }}
          profile-type: MAC_APP_DEVELOPMENT
          bundle-identifiers: ca.hogtownsoftware.examples.HelloMac.HelloMac

      - name: "Import Certificate: Distribution"
        uses: devbotsxyz/import-signing-certificate@main
        with:
          certificate-data: ${{ secrets.DISTRIBUTION_CERTIFICATE_DATA }}
          certificate-passphrase: ${{ secrets.DISTRIBUTION_CERTIFICATE_PASSPHRASE }}
          keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}

      #
      # Fail early on tests.
      #

      - name: "Test"
        uses: devbotsxyz/xcode-test@main

      #
      # Do a developer build that we archive into an .xcarchive.
      #

      - name: "Archive"
        uses: devbotsxyz/xcode-archive@v1

